### ISSUE TITLE
Does not handle != properly

### ISSUE THREAD

**Issue by rassjc** [jazdw/rql-parser#1]
If the query contains 'foo!=3' the parser will identify 'foo!' as the property '=' as the operator and '3' as the value.

**Comment by rassjc** [comment]
Never mind. When they said RQL was a super set of FIQL I thought they meant it. But the != operator is not supported by RQL according to the specification at: http://dundalek.com/rql/draft-zyp-rql-00.html

**Comment by jazdw** [comment]
This is actually supported now as of version 1.0.0-beta.1
