### ISSUE TITLE
Values containing slashes ("/") parse incorrectrly as arrays

### ISSUE THREAD

**Issue by harogaston** [jazdw/rql-parser#5]
It is not possible to write queries in the form of:

`eq(property,/value/containing/slashes)`

because the value field will be converted to [,value,containing,slashes]

As I understand this _parsing_ should only be applied to property fields and not value fields.

Relevant code: https://github.com/jazdw/rql-parser/blob/d19117c958a2140a40071795c341c7a69ce40323/src/main/java/net/jazdw/rql/parser/RQLParser.java#L110-L117

**Comment by jazdw** [comment]
Fixed in v1.0.0-beta.1
