### ISSUE TITLE
Parsing the Sub Beans or Sub Objects

### ISSUE THREAD

**Issue by smittal1209** [jazdw/rql-parser#6]
Hi,
I have a bean which has some nested objects such as another collection of custom objects and I want to filter those on nested properties.
Can you have anything helpful in regards to this or anything in the roadmap or suggest any custom implementation for the same.

**Comment by jazdw** [comment]
Documentation is updated for version 1.0.0-beta.1
https://github.com/jazdw/rql-parser/blob/main/README.md
